Support to Regtest Address
LNP-WG/lnp-node pull request #61
Opened 2022-11-24 04:36 UTC by crisdut

2022-11-24 06:03 UTC, dr-orlovsky commented
Is it that `AddressCompat` doesn't support regtest? If not, it should - since it is a part of the address string; and I will look how to update it first.

`AddressCompat` provides stronger guarantees that the address, once parsed, is supported by the wallet, that is why it is used here

2022-11-24 06:48 UTC, crisdut commented
> Is it that `AddressCompat` doesn't support regtest? If not, it should - since it is a part of the address string; and I will look how to update it first.
> 
> `AddressCompat` provides stronger guarantees that the address, once parsed, is supported by the wallet, that is why it is used here

Hi @dr-orlovsky,

I reverted the change add created a new PR related:

- https://github.com/BP-WG/descriptor-wallet/pull/64

2022-11-24 13:13 UTC, dr-orlovsky commented
Please see my comments in https://github.com/BP-WG/descriptor-wallet/pull/64#issuecomment-1326431925

We need to decide upon that problem first

2022-11-26 18:22 UTC, dr-orlovsky requested changes

2022-11-26 18:22 UTC, dr-orlovsky commented on src/lnpd/funding.rs
> +        let address = Address::from_script(&spk, self.network).unwrap();
Sorry, again, `unwraps` are prohibited outside of the tests

2022-11-28 10:38 UTC, dr-orlovsky approved these changes
ACK 226d2683e1b75dcd992b5ad520f503e284188dd9 as a temporary fix pending https://github.com/LNP-WG/lnp-node/issues/62

2022-11-28 10:38 UTC, merged